### ISSUE TITLE
Cannot open PCB

### ISSUE THREAD

**Issue by yaqwsx** [radxa/radxa-cm-projects#22]
When I try to open the file `CM3_IO_V1.1_20211208.pcb` in PADs Viewer, I get error message: "Unable to load design, cannot open "Downloads/Layout/Layout.lyt". The layout file is missing - it has the extension .lyt". 

Note that Downloads is the directory where I downloaded the PCB. I don't know PADs, but is it possible that you omit to include some files? The same problem appears when I clone the repository.

**Comment by jack-ma** [comment]
I will check this after the holiday(8th, Feb).

**Comment by yaqwsx** [comment]
Hi, any update on this?

**Comment by jack-ma** [comment]
I just downloaded the VX viewer standard version.

PADSViewerVX.2.10.zip

Extract and install it, find 

`C:\MentorGraphics\PADSVX.2.10Viewer\SDD_HOME\Programs\powerpcbviewer.exe`

and open it. You will see the viewer.

User the viewer and open the `CM3_IO_V1.1_20211208.pcb`, I have no problem opening it.

**Comment by tomek-szczesny** [comment]
Perhaps a pdf export of pcb layout could be possible? For us Linux users, you know. :)

**Comment by yaqwsx** [comment]
@jack-ma: I cannot open it. I have PADSViewerVX.2.10, it complains about the missing file. Is it possible that you have the file `LayoutDB.lyt` locally, but it is not committed?

See:
![radxa1](https://user-images.githubusercontent.com/1590880/153463282-acd75992-a859-4dfe-94e9-246c50c33c31.PNG)
![radxa2](https://user-images.githubusercontent.com/1590880/153463288-dcad2f3c-974c-4aa8-ae01-b82a1a518e4f.png)

The version:
![radxa3](https://user-images.githubusercontent.com/1590880/153463289-8b462892-1b69-4614-a552-1696bbbcf17b.png)

Content of the repository:
![radxa4](https://user-images.githubusercontent.com/1590880/153463294-bd1f9cc6-b950-489c-8886-868f0a29665a.png)

**Comment by yaqwsx** [comment]
Am I the only one who cannot open the schematics? If you can open it, could you tell me what I do wrong?

**Comment by tomek-szczesny** [comment]
> Am I the only one who cannot open the schematics? If you can open it, could you tell me what I do wrong?

You mean the PCB layout, right? Schematics work for me, as these are available in pdf. The PCB layout is not that important to me, but it would be a nice touch to export that to pdf as well.

**Comment by jack-ma** [comment]
@yaqwsx I reproduced on a clean installation Windows 10 PC. I have no problem opening the .pcb file with `C:\MentorGraphics\PADSVX.2.10Viewer\SDD_HOME\Programs\powerpcbviewer.exe`. First double click to launch powerpcbviewer, then use File->Open to open the .pcb file. It works just fine.

**Comment by yaqwsx** [comment]
My bad; I was using Pads Browser instead of Pads Viewer. Thank you for your assistance.
