### ISSUE TITLE
Update using RPI CM4 carrier

### ISSUE THREAD

**Issue by Consti10** [radxa/radxa-cm-projects#23]
Hello,

The radxca cm3 has finally arrived (thank you !). As a first step, I've tried updating the firmware.
I installed the board into my rpi carrier and try to follow these steps:
https://wiki.radxa.com/Rock3/installusb-install-radxa-cm3-rpi-cm4-io

But so far to no success. RKDevTool fails with the following message:
"Download boot fail":
![PROBLEM](https://user-images.githubusercontent.com/16462285/155853037-6087c3aa-5226-4e15-8496-57da7f934885.JPG)

Any ideas ? Maybe the board shipped without bootloader ?
The print on the board says Rock3 compute module  v1.1

**Comment by Consti10** [comment]
I have no Idea why, but after clicking some buttons and trying it a couple of times following the tutorial, the flashing seems to have worked:
![Capture](https://user-images.githubusercontent.com/16462285/155853742-18ee0013-7637-4ded-89a3-13a78aa8fc58.JPG)


Now the green LED on the radxca CM3 is blinking, and the LEDs from the CM4 carrier board are
1) Red, solid on
2) green, blinking,
2 times fast, then a break.
aka ON pause OFF pause ON pasue OFF long pause

**Comment by Consti10** [comment]
Any instructions how I can now access the cm4 either via ssh or adb shell ?

**Comment by Consti10** [comment]
It would be generally nice to document:
If radxca cm3 is installed on CM4 carrier:

1) How to boot from sd card
2) How to boot from eMMC ( I assume the board has eMMC, any way to find out)

3) How to boot into bootloader & maskrom ( I think this is done using the buttons on the radxca cm3 itself)

**Comment by Consti10** [comment]
4) What exactly is the effect of jumping
GLOBAL_EN

![Screenshot from 2022-02-26 19-15-41](https://user-images.githubusercontent.com/16462285/155854513-f56edea2-0867-4547-a44d-27ed393457d7.png)

on rpi cm4 carrier and why is it generally needed o get any activity when Radxca CM3 is installed onto RPI CM4 carrier.

**Comment by yaqwsx** [comment]
I was able to flash the CM3 successfully. To be honest, first-time flashing failed, but all consecutive flashes were successful (I use rktool on Linux). The picture with the jumper is misleading, you need to press the button on the board. No jumpers are needed.

**Comment by jack-ma** [comment]
> It would be generally nice to document: If radxca cm3 is installed on CM4 carrier:
> 
> 1. How to boot from sd card
> 2. How to boot from eMMC ( I assume the board has eMMC, any way to find out)
> 3. How to boot into bootloader & maskrom ( I think this is done using the buttons on the radxca cm3 itself)

Boot order for RK356x maskrom is fixed: SPI -> eMMC -> SD/MMC0. In u-boot SPL, the default boot order is: 

    u-boot,spl-boot-order = &sdmmc0, &sdhci, &nandc0, &spi_nand, &spi_nor

So after u-boot SPL is loaded, u-boot in microSD card is first to load and run, then emmc.

> 4. What exactly is the effect of jumping GLOBAL_EN

GLOBAL_EN is to trigger boot(like power button) for CM3 v1.1 version. It connects to pwr_on signal of PMU. For future CM3 version(v1.2 and later), an automatic trigger circuit is added to the CM, so manual trigger is no longer required in the future.

**Comment by Consti10** [comment]
> > It would be generally nice to document: If radxca cm3 is installed on CM4 carrier:
> > 
> > 1. How to boot from sd card
> > 2. How to boot from eMMC ( I assume the board has eMMC, any way to find out)
> > 3. How to boot into bootloader & maskrom ( I think this is done using the buttons on the radxca cm3 itself)
> 
> Boot order for RK356x maskrom is fixed: SPI -> eMMC -> SD/MMC0. In u-boot SPL, the default boot order is:
> 
> ```
> u-boot,spl-boot-order = &sdmmc0, &sdhci, &nandc0, &spi_nand, &spi_nor
> ```
> 
> So after u-boot SPL is loaded, u-boot in microSD card is first to load and run, then emmc.
> 
> > 4. What exactly is the effect of jumping GLOBAL_EN
> 
> GLOBAL_EN is to trigger boot(like power button) for CM3 v1.1 version. It connects to pwr_on signal of PMU. For future CM3 version(v1.2 and later), an automatic trigger circuit is added to the CM, so manual trigger is no longer required in the future.

Thanks for the info.
So this means if I want to boot from SD Card, I just need to put the SD card (with flashed image) in and trigger.
And to boot from eMMC, just remove the SD card and trigger ?

Still wondering why I don't get anything from the board once it is running. Aka the green LED on the board is flashing constantly, and I cannot access the typical adb shell.

**Comment by jack-ma** [comment]
> So this means if I want to boot from SD Card, I just need to put the SD card (with flashed image) in and trigger. And to boot from eMMC, just remove the SD card and trigger ?

Yes. 

> Still wondering why I don't get anything from the board once it is running. Aka the green LED on the board is flashing constantly, and I cannot access the typical adb shell.

Is there anything on the HDMI? I just checked, adb is not enabled by default.

**Comment by Consti10** [comment]
> > So this means if I want to boot from SD Card, I just need to put the SD card (with flashed image) in and trigger. And to boot from eMMC, just remove the SD card and trigger ?
> 
> Yes.
> 
> > Still wondering why I don't get anything from the board once it is running. Aka the green LED on the board is flashing constantly, and I cannot access the typical adb shell.
> 
> Is there anything on the HDMI? I just checked, adb is not enabled by default.

I have not. No display at hand rn. Is ssh enabled by default ?

**Comment by jack-ma** [comment]
Yes, ssh is enabled by default.

**Comment by Consti10** [comment]
Now that I have a display at hand, I can confirm my board is working. As well as ethernet in the rpi official cm4 carrier.
